### ISSUE TITLE
Link preview is not displayed for detail pages 

### ISSUE THREAD

**Issue by manasanavada** [LekoArts/gatsby-starter-tmdb#102]
Hello,

I noticed that the detail pages are not showing the link previews when shared(eg: https://tmdb.lekoarts.de/detail/tv/42009) Although it does have the metadata. Any pointers on how to fix that? 

I'm following a similar routing structure for my codebase and have the same issue with link previews.

**Comment by LekoArts** [comment]
The pages are rendered on the client-side so the HTML is not prerendered and thus some scrapers don't show things.
